# Generated by Django 2.2.7 on 2019-12-22 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBS', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='patient',
            new_name='pat',
        ),
    ]
