# Generated by Django 2.2.7 on 2019-12-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBS', '0002_auto_20191222_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='pat',
            new_name='patient',
        ),
    ]
