# Generated by Django 2.2.7 on 2019-12-22 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HBS', '0003_auto_20191222_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='invoice',
            new_name='invoice1',
        ),
    ]
